### ISSUE TITLE
"Error adding gas" Crashes the Script

### ISSUE THREAD

**Issue by theabominablesasquatch** [Snowball-Finance/snow-harvester#10]
If a new contract for harvesting is added that doesn't provide a permission for the configured harvester, the script aborts. Eventually it would be beneficial to modify the script to ignore contracts it can't connect with or prioritize the ones it can first. Using the pm2, it will keep running the script and aborting as seen below. 

`timestamp=2021-07-28-00:12:14-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:14: web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
timestamp=2021-07-28-00:12:14-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:14: web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
timestamp=2021-07-28-00:12:15-0700 app=HARVEST id=0 type=out message=2021-07-28T00:12:15: WARNING!! Test mode is disabled. Real harvesting might begin!!
timestamp=2021-07-28-00:12:15-0700 app=HARVEST id=0 type=out message=2021-07-28T00:12:15: DiscordBot: Logging in ...
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24: Error adding gas
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24: Error: Returned error: execution reverted
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at Object.ErrorResponse (/home/abominablesasquatch/snow-harvester/node_modules/web3-core-helpers/lib/errors.js:28:19)
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at /home/abominablesasquatch/snow-harvester/node_modules/web3-core-requestmanager/lib/index.js:303:36
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at XMLHttpRequest.request.onreadystatechange (/home/abominablesasquatch/snow-harvester/node_modules/web3-providers-http/lib/index.js:98:13)
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at XMLHttpRequestEventTarget.dispatchEvent (/home/abominablesasquatch/snow-harvester/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at XMLHttpRequest._setReadyState (/home/abominablesasquatch/snow-harvester/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at XMLHttpRequest._onHttpResponseEnd (/home/abominablesasquatch/snow-harvester/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at IncomingMessage.<anonymous> (/home/abominablesasquatch/snow-harvester/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at IncomingMessage.emit (events.js:327:22)
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at endReadableNT (internal/streams/readable.js:1327:12)
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24:   data: null
timestamp=2021-07-28-00:12:24-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:24: }
timestamp=2021-07-28-00:12:25-0700 app=pm2 message=App [HARVEST:0] exited with code [1] via signal [SIGINT]
timestamp=2021-07-28-00:12:25-0700 app=pm2 message=App [HARVEST:0] starting in -fork mode-
timestamp=2021-07-28-00:12:25-0700 app=pm2 message=App [HARVEST:0] online
timestamp=2021-07-28-00:12:28-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:28: web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
timestamp=2021-07-28-00:12:28-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:28: web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
timestamp=2021-07-28-00:12:28-0700 app=HARVEST id=0 type=out message=2021-07-28T00:12:28: WARNING!! Test mode is disabled. Real harvesting might begin!!
timestamp=2021-07-28-00:12:28-0700 app=HARVEST id=0 type=out message=2021-07-28T00:12:28: DiscordBot: Logging in ...
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38: Error adding gas
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38: Error: Returned error: execution reverted
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at Object.ErrorResponse (/home/abominablesasquatch/snow-harvester/node_modules/web3-core-helpers/lib/errors.js:28:19)
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at /home/abominablesasquatch/snow-harvester/node_modules/web3-core-requestmanager/lib/index.js:303:36
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at XMLHttpRequest.request.onreadystatechange (/home/abominablesasquatch/snow-harvester/node_modules/web3-providers-http/lib/index.js:98:13)
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at XMLHttpRequestEventTarget.dispatchEvent (/home/abominablesasquatch/snow-harvester/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at XMLHttpRequest._setReadyState (/home/abominablesasquatch/snow-harvester/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at XMLHttpRequest._onHttpResponseEnd (/home/abominablesasquatch/snow-harvester/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at IncomingMessage.<anonymous> (/home/abominablesasquatch/snow-harvester/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at IncomingMessage.emit (events.js:327:22)
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at endReadableNT (internal/streams/readable.js:1327:12)
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38:   data: null
timestamp=2021-07-28-00:12:38-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:38: }
timestamp=2021-07-28-00:12:39-0700 app=pm2 message=App [HARVEST:0] exited with code [1] via signal [SIGINT]
timestamp=2021-07-28-00:12:39-0700 app=pm2 message=App [HARVEST:0] starting in -fork mode-
timestamp=2021-07-28-00:12:39-0700 app=pm2 message=App [HARVEST:0] online
timestamp=2021-07-28-00:12:42-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:42: web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
timestamp=2021-07-28-00:12:42-0700 app=HARVEST id=0 type=error message=2021-07-28T00:12:42: web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
timestamp=2021-07-28-00:12:43-0700 app=HARVEST id=0 type=out message=2021-07-28T00:12:43: WARNING!! Test mode is disabled. Real harvesting might begin!!
timestamp=2021-07-28-00:12:43-0700 app=HARVEST id=0 type=out message=2021-07-28T00:12:43: DiscordBot: Logging in ...
`

**Comment by theabominablesasquatch** [comment]
resolved by [Pull Request 11](https://github.com/Snowball-Finance/snow-harvester/pull/11)

**Comment by theabominablesasquatch** [comment]
resolved by [Pull Request 11](https://github.com/Snowball-Finance/snow-harvester/pull/11)
