### ISSUE TITLE
Harvester not accounting single-sided harvest

### ISSUE THREAD

**Issue by jomarip** [Snowball-Finance/snow-harvester#17]
Assuming the threshold for harvesting is above $50 bucks in USD equivalent, the single sided harvesting is calling earn well, but not necessarily harvesting appropriately.

This is a manual harvest for Benqi Eth called a few minutes after the automated harvest. There are two possible reasons. 1: the harvesters is fizzling out before completion or 2. the evaluation of the rewards have some issues. 

I will follow up with more details from the log later.
https://cchain.explorer.avax.network/tx/0xe380c2e618662c247169c3a1d87eed209d2d4e2398b4c9e13c1b663331d6be3c/token-transfers

**Comment by jomarip** [comment]
`Failed to sweep for snowglobe 0xa8981Eab82d0a471b37F7d87A221C92aE60c0E00 (USDC.e)
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xb0ada17e715fc93f1fb9874beb6e1bb5ff61c176d3cbcd2ce55942a87f1b0d11",
  "blockNumber": 3764454,
  "contractAddress": null,
  "cumulativeGasUsed": 6028254,
  "effectiveGasPrice": "0x13ca651200",
  "from": "0x096a46142c199c940ffebf34f0fe2f2d674fdb1f",
  "gasUsed": 307667,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xa8981eab82d0a471b37f7d87a221c92ae60c0e00",
  "transactionHash": "0xfde8be9059d6dc25e0cd10aa43e3f40730ee0f2f1404348055f331ec60d5567d",
  "transactionIndex": 24,
  "type": "0x0",
  "events": {}
}
    at Object.TransactionError (/home/snow-harvester/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (/home/snow-harvester/node_modules/web3-core-helpers/lib/errors.js:98:21)
    at /home/snow-harvester/node_modules/web3-core-method/lib/index.js:394:57
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  receipt: {
    blockHash: '0xb0ada17e715fc93f1fb9874beb6e1bb5ff61c176d3cbcd2ce55942a87f1b0d11',
    blockNumber: 3764454,
    contractAddress: null,
    cumulativeGasUsed: 6028254,
    effectiveGasPrice: '0x13ca651200',
    from: '0x096a46142c199c940ffebf34f0fe2f2d674fdb1f',
    gasUsed: 307667,
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    to: '0xa8981eab82d0a471b37f7d87a221c92ae60c0e00',
    transactionHash: '0xfde8be9059d6dc25e0cd10aa43e3f40730ee0f2f1404348055f331ec60d5567d',
    transactionIndex: 24,
    type: '0x0',
    events: {}
  }
}`
